"""add tag model and thumbnail field

Revision ID: 3d8822924074
Revises: cb48ca877272
Create Date: 2025-12-19 04:27:13.804901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d8822924074'
down_revision = 'cb48ca877272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_name'), ['name'], unique=True)

    op.create_table('wallpaper_tags',
    sa.Column('wallpaper_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['wallpaper_id'], ['wallpaper.id'], ),
    sa.PrimaryKeyConstraint('wallpaper_id', 'tag_id')
    )
    with op.batch_alter_table('wallpaper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_filename', sa.String(length=140), nullable=True))
        batch_op.create_unique_constraint('uq_wallpaper_thumbnail_filename', ['thumbnail_filename'])
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallpaper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_constraint('uq_wallpaper_thumbnail_filename', type_='unique')
        batch_op.drop_column('thumbnail_filename')


    op.drop_table('wallpaper_tags')
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_name'))

    op.drop_table('tag')
    # ### end Alembic commands ###
