"""Add status and original_filename to Wallpaper

Revision ID: 9551a9bbb96f
Revises: 9ad1adf371da
Create Date: 2025-12-19 09:15:42.504208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9551a9bbb96f'
down_revision = '9ad1adf371da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallpaper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('original_filename', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallpaper', schema=None) as batch_op:
        batch_op.drop_column('original_filename')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
